com:
    resource: "@ComBundle/Controller/"

trek:
    resource: "@TrekBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_homepage:
    path:     /
    defaults: { _controller: AppBundle:Homepage:homepage }

# trek:
#     path:     /trek/{niveau}
#     defaults: { _controller: TrekBundle:Trek:trek }



user_profil:
    path:     /user/profil
    defaults: { _controller: AppBundle:User:user }

function_search:
    path:    /search
    defaults: { _controller: AppBundle:Search:search }

trek_testmap:
    path:     /trek/map
    defaults: { _controller: TrekBundle:Trek:map }

user_modif:
    path:   /user/profil/user_modif
    defaults: { _controller: AppBundle:Profilmodif:profilmodif}

trek_create:
    path:    /trek/create
    defaults: { _controller: TrekBundle:Trek:create}

trek_list:
    path:    /trek/{niveau}
    defaults: { _controller: TrekBundle:Trek:list}

trek_show:
    path:    /trek/show/{trekid}
    defaults: { _controller: TrekBundle:Trek:show}
