trek:
    resource: "@TrekBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_homepage:
    path:     /
    defaults: { _controller: AppBundle:Homepage:homepage }

trek:
    path:     /trek/{niveau}
    defaults: { _controller: TrekBundle:Trek:trek }

trek_detail:
    path:     /trek/{idTrek}
    defaults: { _controller: AppBundle:Trek:trekDetail }