<?php

namespace TrekBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrekRepository extends EntityRepository
{
}
