<?php

namespace ComBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComRepository extends EntityRepository
{
}
